### ISSUE TITLE
Multi-arch images

### ISSUE THREAD

**Issue by samip5** [lordofsystem/cert-manager-webhook-powerdns#76]
Please compile for arm64 too.

Currently results in `exec /usr/local/bin/webhook: exec format error`

**Comment by lordofsystem** [comment]
I take look at it in the next few days.

**Comment by lordofsystem** [comment]
See #83

**Comment by samip5** [comment]
Unfortunately, this is not complete. That's not arm64 thus doesn't fix the issue.
